### ISSUE TITLE
Pagina quebrada

### ISSUE THREAD

**Issue by aleffita** [rgarbina/CRUD_Cliente_NetCore_MVC#1]
Eu clonei o projeto e executei, sem nenhum erro, porém, ao acessar a url, me deparei com a imagem a baixo. 
Falta alguma configuração ou comando ser rodado ?
Estou utilizando dotnet framework 3.1 e tenho um container docker rodando com o SqlServer configurado para receber conexões como está descrito na connection string. 
![image](https://user-images.githubusercontent.com/26499189/76787583-20ba6d80-6798-11ea-8e3c-7610746d0208.png)

**Comment by rgarbina** [comment]
Boa Tarde Felipe,
Obrigado pelo report,
já foi corrigido e publicado, basta atualizar seu repositório e dar Build.

mas o problema era que não estava baixando os pacotes havia a necessidade em digitar o comando via console ou clicar com o direito no arquivo libman.json no diretório raiz e selecionar restore client side libraries.
também foi adicionado referencia do bootstrap e ajuste do link diretório de referencia.

segue o print [cid:7fd72440-3360-4f29-b74e-df142e460f0b]

Atenciosamente
Raphael Garbina
(17) 981515290
________________________________
De: Felipe Alef <notifications@github.com>
Enviado: segunda-feira, 16 de março de 2020 18:12
Para: rgarbina/CRUD_Cliente_NetCore_MVC <CRUD_Cliente_NetCore_MVC@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [rgarbina/CRUD_Cliente_NetCore_MVC] Pagina quebrada (#1)


Eu clonei o projeto e executei, sem nenhum erro, porém, ao acessar a url, me deparei com a imagem a baixo.
Falta alguma configuração ou comando ser rodado ?
Estou utilizando dotnet framework 3.1 e tenho um container docker rodando com o SqlServer configurado para receber conexões como está descrito na connection string.
[image]<https://user-images.githubusercontent.com/26499189/76787583-20ba6d80-6798-11ea-8e3c-7610746d0208.png>
